export const menuData = [
  {
    id: 1,
    title: "Waffle with Berries",
    type: "Waffle",
    price: 6.50,
    images: {
      mobile: "/public/assets/images/image-waffle-mobile.jpg",
      tablet: "/public/assets/images/image-waffle-tablet.jpg",
      desktop: "/public/assets/images/image-waffle-desktop.jpg",
      thumbnail: "/public/assets/images/image-waffle-thumbnail.jpg",
    },
  },
  {
    id: 2,
    title: "Vanilla Bean Crème Brûlée",
    type: "Crème Brûlée",
    price: 7.00,
    images: {
      mobile: "/public/assets/images/image-creme-brulee-mobile.jpg",
      tablet: "/public/assets/images/image-creme-brulee-tablet.jpg",
      desktop: "/public/assets/images/image-creme-brulee-desktop.jpg",
      thumbnail: "/public/assets/images/image-creme-brulee-thumbnail.jpg",
    },
  },
  {
    id: 3,
    title: "Macaron Mix of Five",
    type: "Macaron",
    price: 8.00,
    images: {
      mobile: "/public/assets/images/image-macaron-mobile.jpg",
      tablet: "/public/assets/images/image-macaron-tablet.jpg",
      desktop: "/public/assets/images/image-macaron-desktop.jpg",
      thumbnail: "/public/assets/images/image-macaron-thumbnail.jpg",
    },
  },
  {
    id: 4,
    title: "Classic Tiramisu",
    type: "Tiramisu",
    price: 5.50,
    images: {
      mobile: "/public/assets/images/image-tiramisu-mobile.jpg",
      tablet: "/public/assets/images/image-tiramisu-tablet.jpg",
      desktop: "/public/assets/images/image-tiramisu-desktop.jpg",
      thumbnail: "/public/assets/images/image-tiramisu-thumbnail.jpg",
    },
  },
  {
    id: 5,
    title: "Pistachio Baklava",
    type: "Baklava",
    price: 4.00,
    images: {
      mobile: "/public/assets/images/image-baklava-mobile.jpg",
      tablet: "/public/assets/images/image-baklava-tablet.jpg",
      desktop: "/public/assets/images/image-baklava-desktop.jpg",
      thumbnail: "/public/assets/images/image-baklava-thumbnail.jpg",
    },
  },
  {
    id: 6,
    title: "Lemon Meringue Pie",
    type: "Pie",
    price: 5.00,
    images: {
      mobile: "/public/assets/images/image-meringue-mobile.jpg",
      tablet: "/public/assets/images/image-meringue-tablet.jpg",
      desktop: "/public/assets/images/image-meringue-desktop.jpg",
      thumbnail: "/public/assets/images/image-meringue-thumbnail.jpg",
    },
  },
  {
    id: 7,
    title: "Red Velvet Cake",
    type: "Cake",
    price: 4.50,
    images: {
      mobile: "/public/assets/images/image-cake-mobile.jpg",
      tablet: "/public/assets/images/image-cake-tablet.jpg",
      desktop: "/public/assets/images/image-cake-desktop.jpg",
      thumbnail: "/public/assets/images/image-cake-thumbnail.jpg",
    },
  },
  {
    id: 8,
    title: "Salted Caramel Brownie",
    type: "Brownie",
    price: 4.50,
    images: {
      mobile: "/public/assets/images/image-brownie-mobile.jpg",
      tablet: "/public/assets/images/image-brownie-tablet.jpg",
      desktop: "/public/assets/images/image-brownie-desktop.jpg",
      thumbnail: "/public/assets/images/image-brownie-thumbnail.jpg",
    },
  },
  {
    id: 9,
    title: "Vanilla Panna Cotta",
    type: "Panna Cotta",
    price: 6.50,
    images: {
      mobile: "/public/assets/images/image-panna-cotta-mobile.jpg",
      tablet: "/public/assets/images/image-panna-cotta-tablet.jpg",
      desktop: "/public/assets/images/image-panna-cotta-desktop.jpg",
      thumbnail: "/public/assets/images/image-panna-cotta-thumbnail.jpg",
    },
  },
];
